"""added not null values

Revision ID: ce164c726d99
Revises: 79e9fce54e9b
Create Date: 2016-08-22 07:45:34.577904

"""

# revision identifiers, used by Alembic.
revision = 'ce164c726d99'
down_revision = '79e9fce54e9b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant', 'ambient_humidity',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('plant', 'soil_humidity',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant', 'soil_humidity',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('plant', 'ambient_humidity',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    ### end Alembic commands ###
