"""generate the table

Revision ID: dc5ea9dee722
Revises: 
Create Date: 2016-08-22 08:05:25.784621

"""

# revision identifiers, used by Alembic.
revision = 'dc5ea9dee722'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('soil_humidity', sa.Float(), nullable=True),
    sa.Column('ambient_humidity', sa.Float(), nullable=True),
    sa.Column('ambient_temperature', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant')
    ### end Alembic commands ###
